### ISSUE TITLE
Cannot install version 0.0.2 on HA 2024.12.3 on docker

### ISSUE THREAD

**Issue by marianobntz** [dermotduffy/hass-web-proxy-integration#48]
## System Information

version | core-2024.12.3
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | null
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51+rpt-rpi-v8
arch | aarch64
timezone | America/Argentina/Buenos_Aires
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4974
Installed Version | 2.0.1
Stage | running
Available Repositories | 1486
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 23, 2025 at 21:00
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
certificate_status | ready
instance_id | fa9d3b61ca514a20911790be5e5f2124
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 10
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 10, 2024 at 10:05
-- | --
current_recorder_run | December 16, 2024 at 09:30
estimated_db_size | 1197.42 MiB
database_engine | postgresql
database_version | 14.4

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 21 / 25
local_online | 14 / 14
debug | failed to load: 

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have installed from HACS the Web Proxy but both when I try to create a new integration and try to enable frigate I get the following error:

`home-assistant  | 2024-12-16 09:31:01.763 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package hass-web-proxy-lib==0.0.7: error: Failed to install: hass_web_proxy_lib-0.0.7-py3-none-any.whl (hass-web-proxy-lib==0.0.7)
home-assistant  |   Caused by: failed to create directory `/usr/local/lib/python3.13/site-packages/hass_web_proxy_lib`: Permission denied (os error 13)
home-assistant  | 2024-12-16 09:31:01.765 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'frigate': Requirements for frigate not found: ['hass-web-proxy-lib==0.0.7'].`

I tried getting inside the docker image and change the permissions but I am not sure it works.

I run ha on docker with a non-root user. I am trying to use this for Frigate 5.6.0 integration. 

Help is appreciated

### Reproduction steps

1. Install web proxy 0.0.2 from hacs
2. Try to enable a new integration or 
3. Try to enable frigate integration
...

### Debug logs

```text
all I get is this error:

home-assistant  | 2024-12-16 09:33:17.181 INFO (MainThread) [homeassistant.requirements] Multiple attempts to install hass-web-proxy-lib==0.0.7 failed, install will be retried after next configuration check or restart
home-assistant  | 2024-12-16 09:33:17.181 ERROR (MainThread) [aiohttp.server] Error handling request
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
home-assistant  |     resp = await request_handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
home-assistant  |     response = await handler(request)
home-assistant  |                ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
home-assistant  |     result = await handler(request, **request.match_info)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
home-assistant  |     return await func(self, request, *args, **kwargs)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
home-assistant  |     return await method(view, request, data, *args, **kwargs)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
home-assistant  |     return await self._post_impl(request, data)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
home-assistant  |     return await super()._post_impl(request, data)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
home-assistant  |     result = await self._flow_mgr.async_init(
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |     ...<2 lines>...
home-assistant  |     )
home-assistant  |     ^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1315, in async_init
home-assistant  |     flow, result = await self._async_init(flow_id, handler, context, data)
home-assistant  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1340, in _async_init
home-assistant  |     flow = await self.async_create_flow(handler, context=context, data=data)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1536, in async_create_flow
home-assistant  |     handler = await _async_get_flow_handler(
home-assistant  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |         self.hass, handler_key, self._hass_config
home-assistant  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |     )
home-assistant  |     ^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3333, in _async_get_flow_handler
home-assistant  |     await _load_integration(hass, domain, hass_config)
home-assistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3310, in _load_integration
home-assistant  |     await async_process_deps_reqs(hass, hass_config, integration)
home-assistant  |   File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
home-assistant  |     await requirements.async_get_integration_with_requirements(
home-assistant  |         hass, integration.domain
home-assistant  |     )
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
home-assistant  |     return await manager.async_get_integration_with_requirements(domain)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
home-assistant  |     await future
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
home-assistant  |     await self._async_process_integration(integration, done)
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
home-assistant  |     await self.async_process_requirements(
home-assistant  |         integration.domain, integration.requirements
home-assistant  |     )
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 264, in async_process_requirements
home-assistant  |     self._raise_for_failed_requirements(name, missing)
home-assistant  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
home-assistant  |     raise RequirementsNotFound(integration, [req])
home-assistant  | homeassistant.requirements.RequirementsNotFound: Requirements for hass_web_proxy not found: ['hass-web-proxy-lib==0.0.7'].


home-assistant  | 2024-12-16 09:30:59.436 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: valve raspi_huerta riego_frente
home-assistant  | 2024-12-16 09:30:59.779 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package hass-web-proxy-lib==0.0.7: error: Failed to install: hass_web_proxy_lib-0.0.7-py3-none-any.whl (hass-web-proxy-lib==0.0.7)
home-assistant  |   Caused by: failed to create directory `/usr/local/lib/python3.13/site-packages/hass_web_proxy_lib`: Permission denied (os error 13)
home-assistant  | 2024-12-16 09:30:59.779 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of hass-web-proxy-lib==0.0.7
home-assistant  | 2024-12-16 09:30:59.953 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'calefaccion_current_temperature' when rendering '{{ value_json.calefaccion_current_temperature }}'
home-assistant  | 2024-12-16 09:30:59.955 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'calefaccion_current_temperature' when rendering '{{ value_json.calefaccion_current_temperature }}'
home-assistant  | 2024-12-16 09:30:59.956 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'calefaccion_humidity' when rendering '{{ value_json.calefaccion_humidity }}'
home-assistant  | 2024-12-16 09:31:00.760 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package hass-web-proxy-lib==0.0.7: error: Failed to install: hass_web_proxy_lib-0.0.7-py3-none-any.whl (hass-web-proxy-lib==0.0.7)
home-assistant  |   Caused by: failed to create directory `/usr/local/lib/python3.13/site-packages/hass_web_proxy_lib`: Permission denied (os error 13)
home-assistant  | 2024-12-16 09:31:00.761 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of hass-web-proxy-lib==0.0.7
home-assistant  | 2024-12-16 09:31:00.804 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up ping.binary_sensor
home-assistant  | 2024-12-16 09:31:00.806 INFO (MainThread) [homeassistant.components.device_tracker] Setting up ping.device_tracker
home-assistant  | 2024-12-16 09:31:00.807 INFO (MainThread) [homeassistant.components.sensor] Setting up ping.sensor
home-assistant  | 2024-12-16 09:31:00.809 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up ping.binary_sensor
home-assistant  | 2024-12-16 09:31:00.811 INFO (MainThread) [homeassistant.components.device_tracker] Setting up ping.device_tracker
home-assistant  | 2024-12-16 09:31:00.812 INFO (MainThread) [homeassistant.components.sensor] Setting up ping.sensor
home-assistant  | 2024-12-16 09:31:01.763 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package hass-web-proxy-lib==0.0.7: error: Failed to install: hass_web_proxy_lib-0.0.7-py3-none-any.whl (hass-web-proxy-lib==0.0.7)
home-assistant  |   Caused by: failed to create directory `/usr/local/lib/python3.13/site-packages/hass_web_proxy_lib`: Permission denied (os error 13)
home-assistant  | 2024-12-16 09:31:01.765 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'frigate': Requirements for frigate not found: ['hass-web-proxy-lib==0.0.7'].
```

**Comment by dermotduffy** [comment]
Are you simply trying to install Frigate, or do you actually need this integration (typically used for the [`frigate-card`](https://github.com/dermotduffy/frigate-hass-card) for non-Frigate cameras.

If you're just trying to install Frigate, and ran into this error:

> Setup failed for custom integration 'frigate': Requirements for frigate not found: ['hass-web-proxy-lib==0.0.7'].

You should read this pinned issue & workaround: https://github.com/blakeblackshear/frigate-hass-integration/issues/762

**Comment by dermotduffy** [comment]
Please see the workaround I linked to. In any case, your issue is not related to the integration in which you filed this issue.

**Comment by marianobntz** [comment]
which workaround? downgrade frigate to 5.4.0 or install using pip? (pip install hass-web-proxy-lib==0.0.7)

**Comment by marianobntz** [comment]
tried downgrading to 5.4.0 and upgrading to 5.6.0 and still not working... please advise which workaround you are referring to. Thanks

**Comment by dermotduffy** [comment]
I linked to it in my reply.

**Comment by dermotduffy** [comment]
https://github.com/blakeblackshear/frigate-hass-integration/issues/762#issuecomment-2530078843

**Comment by marianobntz** [comment]
> [blakeblackshear/frigate-hass-integration#762 (comment)](https://github.com/blakeblackshear/frigate-hass-integration/issues/762#issuecomment-2530078843)

Tried that (the workaround for HA 2024.12) (to create an empty /.dockerenv file)  but still no luck with HA 2024.12

**Comment by marianobntz** [comment]
what worked is to create a /.local directory with 777 permission. then install hass-web-proxy with this command: 

`docker compose exec home-assistant pip install hass-web-proxy-lib==0.0.7`

Then a reload and restart made it work.
